### ISSUE TITLE
⚠️ Hardcoded API Key in the Code

### ISSUE THREAD

**Issue by darkermango** [im-yjoshua/Weather_StreamLit_App#1]
# Hardcoded API Key
Hey I found you have a hardcoded API key in the source code. It's generally not a great idea to leave sensitive info like this directly in the code.

## Location
The hardcoded API key is at `weather_app.py at line 24`

### Actions
- Remove the hardcoded API key from the source code.
- Regenerate the API key to ensure that the exposed key is no longer usable.
- Use environment variables or a secure key management system to manage the API key.
- Update the .gitignore file to prevent sensitive files from being accidentally committed.

   **Thank You!**

**Comment by im-yjoshua** [comment]
Thanks a lot, @cheaderthecoder for pointing this out, and for your feedback. I have updated the codebase. Thanks again!

**Comment by darkermango** [comment]
@im-yjoshua Np always happy to help.
